import type { NextPage } from "next";
import Head from "next/head";
import Typography from "@mui/material/Typography";
import Box from "@mui/material/Box";
import Grid from "@mui/material/Grid";
import { Button, Card, CardContent, CardMedia, Tab, Tabs } from "@mui/material";
import React from "react";
import CLOTHES from "./helpers/clothes";

interface TabPanelProps {
	children?: React.ReactNode;
	index: number;
	value: number;
}

function TabPanel(props: TabPanelProps) {
	const { children, value, index, ...other } = props;

	return (
		<Box
			role="tabpanel"
			hidden={value !== index}
			id={`simple-tabpanel-${index}`}
			aria-labelledby={`simple-tab-${index}`}
			sx={{ width: "100%" }}
			{...other}
		>
			{value === index && (
				<Box sx={{ p: 3 }}>
					<Typography>{children}</Typography>
				</Box>
			)}
		</Box>
	);
}

function a11yProps(index: number) {
	return {
		id: `simple-tab-${index}`,
		"aria-controls": `simple-tabpanel-${index}`,
	};
}

const Home: NextPage = () => {
	const [value, setValue] = React.useState(0);

	const handleChange = (event: React.SyntheticEvent, newValue: number) => {
		setValue(newValue);
	};

	return (
		<div>
			<Head>
				<title>Hola mundo</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				{/* <link rel="icon" href="/favicon.ico" /> */}
			</Head>

			<main>
				<Box
					sx={{
						display: "flex",
						justifyContent: "center",
						marginTop: 8,
					}}
				>
					<Grid container xs={9}>
						<Typography
							variant="h4"
							color="initial"
							sx={{ width: "100%", textAlign: "center" }}
						>
							Productos
						</Typography>
						<Box sx={{ width: "100%", marginTop: 2 }}>
							<Tabs
								value={value}
								onChange={handleChange}
								aria-label="basic tabs example"
								centered
							>
								<Tab
									label="NUEVOS PRODUCTOS"
									{...a11yProps(0)}
								/>
								<Tab label="LO MAS VENDIDO" {...a11yProps(1)} />
								<Tab label="EN DESCUENTO" {...a11yProps(2)} />
							</Tabs>
						</Box>
						<TabPanel value={value} index={0}>
							<Grid container spacing={2}>
								{CLOTHES.map((card, i) => (
									<Grid item xs={4} key={i}>
										<Card elevation={0}>
											<CardMedia
												component="img"
												height="400"
												image={card.image.src}
												alt="green iguana"
											/>
											<CardContent
												sx={{ textAlign: "center" }}
											>
												<Button size="small">
													{card.name}{" "}
												</Button>
												<Typography
													gutterBottom
													variant="body1"
												>
													{card.price}
												</Typography>
											</CardContent>
										</Card>
									</Grid>
								))}
							</Grid>
						</TabPanel>
						<TabPanel value={value} index={1}>
							<Grid container spacing={2}>
								{CLOTHES.map((card, i) => (
									<Grid item xs={4} key={i}>
										<Card elevation={0}>
											<CardMedia
												component="img"
												height="400"
												image={card.image.src}
												alt="green iguana"
											/>
											<CardContent
												sx={{ textAlign: "center" }}
											>
												<Button size="small">
													{card.name}{" "}
												</Button>
												<Typography
													gutterBottom
													variant="body1"
												>
													{card.price}
												</Typography>
											</CardContent>
										</Card>
									</Grid>
								))}
							</Grid>
						</TabPanel>
						<TabPanel value={value} index={2}></TabPanel>
					</Grid>
				</Box>
			</main>
		</div>
	);
};

export default Home;
